apiVersion: v1
kind: Service
metadata:
  name: stock-reader-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31111
      protocol: TCP
  selector:
    app: stock-reader
