apiVersion: v1
kind: Service
metadata:
  name: stock-trading-algorithms-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 31112
      protocol: TCP
  selector:
    app: stock-trading-algorithms
