apiVersion: v1
kind: Pod
metadata:
  name: stock-reader
  labels:
    app: stock-reader
spec:
  containers:
    - name: stock-reader
      image: temmink/stock-reader:latest
      ports:
        - containerPort: 8080
      env:
        - name: db.url
          value: "r2dbc:postgresql://192.168.49.1:5432"
        - name: spring.flyway.url
          value: "jdbc:postgresql://192.168.49.1:5432/stocks"
        - name: spring.flyway.user
          value: "postgres"
        - name: spring.flyway.password
          value: "postgres"
        - name: db.username
          value: "postgres"
        - name: db.password
          value: "postgres"