apiVersion: v1
kind: Pod
metadata:
  name: stock-reader
  labels:
    app: web
spec:
  containers:
    - name: stock-reader
      image: temmink/gimmethemoney:0.1
      ports:
        - containerPort: 8080
      env:
        - name: db.url
          value: "r2dbc:postgresql://192.168.49.1:5432"
        - name: spring.flyway.url
          value: "jdbc:postgresql://192.168.49.1:5432/stocks"
